Updated and simplified onboarding pages
Y-Foundry-Dao/yfd-docs pull request #75
Opened 2022-12-25 21:41 UTC by JunMagic88

2022-12-25 21:41 UTC, JunMagic88 commented
Updated and simplified Built on the Blockchain and Seeding the Cosmos

2022-12-25 21:49 UTC, JunMagic88 reviewed
Updated onboarding pages

2022-12-26 14:07 UTC, crashtestdumb1 requested changes
Just a couple of comments. Overall very nice. I appreciate the more concise language and removing some of the content that is discussed in later sections.

2022-12-26 14:07 UTC, crashtestdumb1 commented on docs/_onboard/seeding-the-cosmos.md
> +Y-Foundry DAO is a community born out of frustration and contempt with opague and exploitative crypto projects. These projects are often run by cult-like personalities who extracts value from uninfor
"opague" should be "opaque"
Not sure if "cult-like personalities" is accurate. Cult-like would be describing the followers not the leaders. Maybe "personalities who abuse a cult-like following with their uninformed participants to enrich their own pockets..."

2022-12-26 20:40 UTC, JunMagic88 commented on docs/_onboard/seeding-the-cosmos.md
> +Y-Foundry DAO is a community born out of frustration and contempt with opague and exploitative crypto projects. These projects are often run by cult-like personalities who extracts value from uninfor
Discussed with Ray - this is an old page and is not longer in /docs. should be removed

2022-12-26 20:41 UTC, JunMagic88 commented on _drafts/about/about.md
> +_Trustless execution of treasury actions based on on-onchain votes - no one has privileged access, not even the core team._
Discussed with Ray - this is an old page and should be removed.

2022-12-28 16:20 UTC, crashtestdumb1 approved these changes

2022-12-28 16:20 UTC, merged